version: 2
mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt

# only for sphinx ... not works with mkdocs...
formats:
  - pdf
  - epub


build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  #jobs:
    #pre_build:
      # - python -m sphinx -b linkcheck -D linkcheck_timeout=1 docs/ _build/linkcheck
      # - pydoc-markdown --build --site-dir "$PWD/_build/html"
    # pre_install:
    #   - bash ./scripts/pre_install.sh
    #   - git update-index --assume-unchanged environment.yml docs/conf.py