[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "e-carnetV2"
authors = [{name = "Gaillot", email = ";thierry@tr-esolutions.com"}]
dynamic = ["version", "description"]
